#[rustfmt::skip]
mod tests {
use serde_json::Value; use std::process::Command; use std::time::{SystemTime,UNIX_EPOCH};
const VALID:&str=concat!(env!("CARGO_MANIFEST_DIR"),"/../../fixtures/jacoco/valid-methods.xml"); const MALFORMED:&str=concat!(env!("CARGO_MANIFEST_DIR"),"/../../fixtures/jacoco/malformed.xml");
fn run(a:&[&str])->(i32,String,String){let o=Command::new(std::env::var("CARGO_BIN_EXE_codegauge").unwrap()).args(a).output().unwrap();(o.status.code().unwrap(),String::from_utf8(o.stdout).unwrap(),String::from_utf8(o.stderr).unwrap())}
fn code(s:&str)->String{serde_json::from_str::<Value>(s).unwrap()["code"].as_str().unwrap().into()}
#[test]fn profiles_and_version_are_exact(){assert_eq!(run(&["profiles"]),(0,"java-jacoco-v1\n".into(),"".into()));assert_eq!(run(&["version"]),(0,concat!("codegauge ",env!("CARGO_PKG_VERSION"),"\n").into(),"".into()));}
#[test]fn analyze_emits_one_json_document_and_maps_outcomes(){let(s,o,e)=run(&["analyze","--profile","java-jacoco-v1","--input",VALID,"--format","json"]);assert_eq!(s,6);assert_eq!(serde_json::from_str::<Value>(&o).unwrap()["analysis"]["status"],"PARTIAL");assert!(!e.is_empty()&&!o.contains("PASS")&&!o.contains("FAIL"));for(a,x)in[(vec!["analyze","--profile","java-jacoco-v1","--input","missing.xml","--format","json"],(3,"INPUT_NOT_FOUND")),(vec!["analyze","--profile","unknown-v1","--input","missing.xml","--format","json"],(4,"UNSUPPORTED_PROFILE")),(vec!["analyze","--profile","java-jacoco-v1","--input",MALFORMED,"--format","json"],(5,"INVALID_INPUT"))]{let(s,o,_)=run(&a);assert_eq!((s,code(&o)),(x.0,x.1.into()));}}
#[test]fn args_partial_incompatible_and_internal_exit_are_stable(){let(s,o,e)=run(&["analyze","--profile","java-jacoco-v1","--input","missing.xml","--format","text"]);assert_eq!((s,code(&o)),(2,"CLI_ERROR".into()));assert!(!e.is_empty());let f=std::env::temp_dir().join(format!("codegauge-full-{}",SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos()));std::fs::write(&f,"<report><class name=\"C\"><method name=\"m\" desc=\"()V\"><counter type=\"COMPLEXITY\" missed=\"0\" covered=\"1\"/><counter type=\"INSTRUCTION\" missed=\"0\" covered=\"1\"/></method></class></report>").unwrap();let(s,o,_)=run(&["analyze","--profile","java-jacoco-v1","--input",f.to_str().unwrap(),"--format","json"]);std::fs::remove_file(f).unwrap();assert_eq!(s,0);assert_eq!(serde_json::from_str::<Value>(&o).unwrap()["analysis"]["status"],"COMPLETE");let p=std::env::temp_dir().join(format!("codegauge-empty-{}",SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos()));std::fs::write(&p,"<report/>").unwrap();let(s,o,_)=run(&["analyze","--profile","java-jacoco-v1","--input",p.to_str().unwrap(),"--format","json"]);std::fs::remove_file(p).unwrap();assert_eq!((s,code(&o)),(6,"INCOMPATIBLE_MEASUREMENTS".into()));assert_eq!(codegauge_application::exit_code_for_error(codegauge_model::ErrorCode::InternalError),10);}
}
