[package]
name = "codegauge-cli"
version = "0.3.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
description = "Deterministic CodeGauge command-line interface"
exclude = ["tests/**"]

[[bin]]
name = "codegauge"
path = "src/main.rs"

[dependencies]
codegauge-application = { version = "0.3.0", path = "../codegauge-application" }
codegauge-model = { version = "0.3.0", path = "../codegauge-model" }
codegauge-provider-jacoco = { version = "0.3.0", path = "../codegauge-provider-jacoco" }
clap.workspace = true

[dev-dependencies]
serde_json.workspace = true
